In [34]:
import pandas as pd

In [35]:
df = pd.read_csv('london_merged.csv')
print(" "*10)
print("printing the first some rows  of the data ")
print(" "*10)
print(df.head())
print(" "*30)
print("printing the information")
print(" "*10)
print(df.info())
print(" "*30)
print("printing the shape of the data")
print(" "*10)
print(df.shape)
print(" "*30)
print("printing the columns of the data")
print(" "*10)
print(df.columns.tolist())
print(" "*30)
print("printing the statistics of the data")
print(" "*10)
print(df.describe())

printing the first some rows  of the data

             timestamp  cnt   t1   t2    hum  wind_speed  weather_code  \
0  2015-01-04 00:00:00  182  3.0  2.0   93.0         6.0           3.0
1  2015-01-04 01:00:00  138  3.0  2.5   93.0         5.0           1.0
2  2015-01-04 02:00:00  134  2.5  2.5   96.5         0.0           1.0
3  2015-01-04 03:00:00   72  2.0  2.0  100.0         0.0           1.0
4  2015-01-04 04:00:00   47  2.0  0.0   93.0         6.5           1.0

   is_holiday  is_weekend  season
0         0.0         1.0     3.0
1         0.0         1.0     3.0
2         0.0         1.0     3.0
3         0.0         1.0     3.0
4         0.0         1.0     3.0

printing the information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  object
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB
None

printing the shape of the data

(17414, 10)

printing the columns of the data

['timestamp', 'cnt', 't1', 't2', 'hum', 'wind_speed', 'weather_code', 'is_holiday', 'is_weekend', 'season']

printing the statistics of the data

                cnt            t1            t2           hum    wind_speed  \
count  17414.000000  17414.000000  17414.000000  17414.000000  17414.000000
mean    1143.101642     12.468091     11.520836     72.324954     15.913063
std     1085.108068      5.571818      6.615145     14.313186      7.894570
min        0.000000     -1.500000     -6.000000     20.500000      0.000000
25%      257.000000      8.000000      6.000000     63.000000     10.000000
50%      844.000000     12.500000     12.500000     74.500000     15.000000
75%     1671.750000     16.000000     16.000000     83.000000     20.500000
max     7860.000000     34.000000     34.000000    100.000000     56.500000

       weather_code    is_holiday    is_weekend        season
count  17414.000000  17414.000000  17414.000000  17414.000000
mean       2.722752      0.022051      0.285403      1.492075
std        2.341163      0.146854      0.451619      1.118911
min        1.000000      0.000000      0.000000      0.000000
25%        1.000000      0.000000      0.000000      0.000000
50%        2.000000      0.000000      0.000000      1.000000
75%        3.000000      0.000000      1.000000      2.000000
max       26.000000      1.000000      1.000000      3.000000

In [36]:
df['weather_code'].value_counts().sort_values(ascending=False)

weather_code
1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: count, dtype: int64

In [37]:
df['season'].value_counts().sort_values()

season
2.0    4303
3.0    4330
1.0    4387
0.0    4394
Name: count, dtype: int64

In [38]:
df.dtypes

timestamp        object
cnt               int64
t1              float64
t2              float64
hum             float64
wind_speed      float64
weather_code    float64
is_holiday      float64
is_weekend      float64
season          float64
dtype: object

In [39]:
#find
#duplicated
#missing
#outliers
#data types
#value distribution


#question to ask from teh data

# what is the effect of every column on the rentals
#in which season does the cnt is max
# Do people rent more on holidays or normal days?
# Weekdays vs weekends — who rents more?
#whqts teh range of temp at that day where the rental is max
#at what time people rent most bikes

In [40]:
df.isnull().sum()

timestamp       0
cnt             0
t1              0
t2              0
hum             0
wind_speed      0
weather_code    0
is_holiday      0
is_weekend      0
season          0
dtype: int64

In [41]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
17409    False
17410    False
17411    False
17412    False
17413    False
Length: 17414, dtype: bool

In [42]:
season_mapping = {
   '0.0' : 'spring',
    '1.0' : 'summer',
    '2.0' : 'fall',
    '3.0' : 'winter'
}
df['season'] = df['season'].astype(str)
df['season'] = df['season'].map(season_mapping)

In [43]:
weqther_mapping = {
    '1.0':'Clear',
    '2.0':'Scattered clouds',
    '3.0':'Broken clouds',
    '4.0':'Cloudy',
    '7.0':'Rain',
    '10.0':'Rain with thunderstorm',
    '26.0':'Snowfall'
}
df['weather'] = df['weather_code'].astype(str)
df['weather'] = df['weather'].map(weqther_mapping)

In [44]:
df

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season,weather
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,winter,Broken clouds
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,winter,Clear
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,winter,Clear
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,winter,Clear
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,winter,Clear
...,...,...,...,...,...,...,...,...,...,...,...
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,winter,Broken clouds
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,winter,Cloudy
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,winter,Cloudy
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,winter,Cloudy
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,winter,Scattered clouds

In [45]:
df['season'].value_counts()

season
spring    4394
summer    4387
winter    4330
fall      4303
Name: count, dtype: int64

In [49]:
df.to_excel('london_merged_new.xlsx')